menu_items = [  
# Starters - Veg
    {"id": "s_v_1", "category": "Starters - Veg", "item_name": "Veg Noodles (6 Pcs)", "price": 65, "image": "food_items/item1.jpg", "description": "Classic noodles, sautéed with fresh vegetables and aromatic spices."},
    {"id": "s_v_2", "category": "Starters - Veg", "item_name": "Veg Momos (5 Pcs)", "price": 65, "image": "food_items/item2.jpg", "description": "Steamed dumplings filled with seasoned vegetables."},
    {"id": "s_v_3", "category": "Starters - Veg", "item_name": "Corn Cheese Ball (5 Pcs)", "price": 80, "image": "food_items/item1.jpg", "description": "Crispy fried balls with sweet corn and melted cheese."},
    {"id": "s_v_4", "category": "Starters - Veg", "item_name": "Corn Cheese Nuggets (5 Pcs)", "price": 80, "image": "food_items/item2.jpg", "description": "Golden nuggets bursting with corn and cheese flavor."},
    {"id": "s_v_5", "category": "Starters - Veg", "item_name": "Veg Lollipop (3 Pcs)", "price": 100, "image": "food_items/item1.jpg", "description": "Vegetable fritters shaped like lollipops, crispy and savory."},
    # Starters - Non-Veg
    {"id": "s_nv_1", "category": "Starters - Non-Veg", "item_name": "Chicken Lollipop (3 Pcs)", "price": 120, "image": "food_items/item2.jpg", "description": "Juicy chicken drumettes, deep-fried to perfection."},
    {"id": "s_nv_2", "category": "Starters - Non-Veg", "item_name": "Chicken Strips (4 Pcs)", "price": 100, "image": "food_items/item1.jpg", "description": "Tender chicken strips, lightly breaded and fried."},
    {"id": "s_nv_3", "category": "Starters - Non-Veg", "item_name": "Chicken Wings (4 Pcs)", "price": 120, "image": "food_items/item2.jpg", "description": "Crispy chicken wings, seasoned and fried."},
    {"id": "s_nv_4", "category": "Starters - Non-Veg", "item_name": "Chicken Crispy", "price": 130, "image": "food_items/item1.jpg", "description": "Crispy fried chicken, a perfect appetizer."},
    # Momos - Veg
    {"id": "m_v_1", "category": "Momos - Veg", "item_name": "Veg Momos (5 Pcs)", "price": 70, "image": "food_items/item2.jpg", "description": "Steamed dumplings filled with seasoned vegetables."},
    {"id": "m_v_2", "category": "Momos - Veg", "item_name": "Veg Momos (4 Pcs)", "price": 65, "image": "food_items/item1.jpg", "description": "Steamed dumplings filled with seasoned vegetables."},
    # Momos - Non-Veg
    {"id": "m_nv_1", "category": "Momos - Non-Veg", "item_name": "Chicken Momos", "price": 85, "image": "food_items/item2.jpg", "description": "Steamed dumplings filled with juicy chicken."},
    {"id": "m_nv_2", "category": "Momos - Non-Veg", "item_name": "Peri Peri Momos", "price": 90, "image": "food_items/item1.jpg", "description": "Spicy peri peri flavored chicken momos."},
    # Sandwich - Veg
    {"id": "s_v_s_1", "category": "Sandwich - Veg", "item_name": "Veg Cheese Sandwich", "price": 65, "image": "food_items/item2.jpg", "description": "Grilled sandwich with fresh vegetables and cheese."},
    {"id": "s_v_s_2", "category": "Sandwich - Veg", "item_name": "Paneer Sandwich", "price": 70, "image": "food_items/item1.jpg", "description": "Toasted sandwich with flavorful paneer filling."},
    {"id": "s_v_s_3", "category": "Sandwich - Veg", "item_name": "Bombay Veg Sandwich", "price": 75, "image": "food_items/item2.jpg", "description": "Spicy Bombay-style vegetable sandwich."},
    # Sandwich - Non-Veg
    {"id": "s_nv_s_1", "category": "Sandwich - Non-Veg", "item_name": "Chicken Sandwich", "price": 80, "image": "app/static/images/sandwich.jpg", "description": "Classic sandwich with shredded chicken filling."},
    {"id": "s_nv_s_2", "category": "Sandwich - Non-Veg", "item_name": "Chicken Cheese Sandwich", "price": 90, "image": "food_items/item2.jpg", "description": "Chicken sandwich with melted cheese."},
    {"id": "s_nv_s_3", "category": "Sandwich - Non-Veg", "item_name": "BBQ Chicken Sandwich", "price": 90, "image": "food_items/item1.jpg", "description": "Tangy BBQ chicken in a grilled sandwich."},
    {"id": "s_nv_s_4", "category": "Sandwich - Non-Veg", "item_name": "Bombay Chicken Sandwich", "price": 95, "image": "food_items/item2.jpg", "description": "Spicy Bombay-style chicken sandwich."},
    # Wraps - Veg
    {"id": "w_v_1", "category": "Wrap - Veg", "item_name": "Veg Wrap", "price": 60, "image": "food_items/item1.jpg", "description": "Fresh vegetables wrapped in a soft tortilla."},
    {"id": "w_v_2", "category": "Wrap - Veg", "item_name": "Paneer Wrap", "price": 80, "image": "food_items/item2.jpg", "description": "Spiced paneer wrapped in a soft tortilla."},
    # Wraps - Non-Veg
    {"id": "w_nv_1", "category": "Wrap - Non-Veg", "item_name": "Chicken Tikka Wrap", "price": 80, "image": "food_items/item1.jpg", "description": "Spicy chicken tikka wrapped in a tortilla."},
    {"id": "w_nv_2", "category": "Wrap - Non-Veg", "item_name": "Peri Peri Wrap", "price": 80, "image": "food_items/item2.jpg", "description": "Fiery peri peri chicken wrapped in a tortilla."},
    {"id": "w_nv_3", "category": "Wrap - Non-Veg", "item_name": "BBQ Chicken Wrap", "price": 85, "image": "food_items/item1.jpg", "description": "Smoky BBQ chicken wrapped in a tortilla."},
    # Burger
    {"id": "b_1", "category": "Burger", "item_name": "Veg Burger", "price": 80, "image": "food_items/item2.jpg", "description": "Classic veggie patty burger."},
    {"id": "b_2", "category": "Burger", "item_name": "Chicken Burger", "price": 90, "image": "food_items/item1.jpg", "description": "Juicy chicken patty burger."},
    {"id": "b_3", "category": "Burger", "item_name": "Zinger Burger", "price": 100, "image": "food_items/item2.jpg", "description": "Crispy chicken zinger burger."},
    # Pizza - Veg
    {"id": "p_v_1", "category": "Pizza - Veg", "item_name": "Veg Pizza", "price": 100, "image": "food_items/item1.jpg", "description": "Classic vegetable topping pizza."},
    {"id": "p_v_2", "category": "Pizza - Veg", "item_name": "Sweet Corn Pizza", "price": 110, "image": "food_items/item2.jpg", "description": "Pizza loaded with sweet corn."},
    {"id": "p_v_3", "category": "Pizza - Veg", "item_name": "Paneer Pizza", "price": 120, "image": "food_items/item1.jpg", "description": "Pizza topped with succulent paneer cubes."},
    {"id": "p_v_4", "category": "Pizza - Veg", "item_name": "Peri Peri Paneer Pizza", "price": 130, "image": "food_items/item2.jpg", "description": "Spicy peri peri paneer pizza."},
    # Pizza - Non-Veg
    {"id": "p_nv_1", "category": "Pizza - Non-Veg", "item_name": "Chicken Tikka Pizza", "price": 130, "image": "food_items/item1.jpg", "description": "Pizza topped with spicy chicken tikka."},
    {"id": "p_nv_2", "category": "Pizza - Non-Veg", "item_name": "Peri Peri Chicken Pizza", "price": 140, "image": "food_items/item2.jpg", "description": "Fiery peri peri chicken pizza."},
    {"id": "p_nv_3", "category": "Pizza - Non-Veg", "item_name": "BBQ Chicken Pizza", "price": 140, "image": "food_items/item1.jpg", "description": "Smoky BBQ chicken pizza."},
    {"id": "p_nv_4", "category": "Pizza - Non-Veg", "item_name": "Chicken Golden Pizza", "price": 150, "image": "food_items/item2.jpg", "description": "Rich golden chicken pizza, a delightful treat."},
    # Dessert & Ice Cream
    {"id": "d_ic_1", "category": "Dessert & Ice Cream", "item_name": "Royal Falooda", "price": 130, "image": "food_items/item1.jpg", "description": "Refreshing falooda with ice cream, vermicelli, and rose syrup."},
    {"id": "d_ic_2", "category": "Dessert & Ice Cream", "item_name": "Dry Fruit Falooda", "price": 100, "image": "food_items/item2.jpg", "description": "Falooda with assorted dry fruits."},
    {"id": "d_ic_3", "category": "Dessert & Ice Cream", "item_name": "Brownie with Ice Cream", "price": 120, "image": "food_items/item1.jpg", "description": "Warm brownie served with a scoop of ice cream."},
    {"id": "d_ic_4", "category": "Dessert & Ice Cream", "item_name": "Sizzling Brownie", "price": 120, "image": "food_items/item2.jpg", "description": "Hot brownie served on a sizzler plate with ice cream and chocolate sauce."},
    # Ice Cream (Single Scoop)
    {"id": "ic_ss_1", "category": "Ice Cream (Single Scoop)", "item_name": "Vanilla", "price": 40, "image": "food_items/item1.jpg", "description": "Classic vanilla ice cream."},
    {"id": "ic_ss_2", "category": "Ice Cream (Single Scoop)", "item_name": "Chocolate", "price": 40, "image": "food_items/item2.jpg", "description": "Rich chocolate ice cream."},
    {"id": "ic_ss_3", "category": "Ice Cream (Single Scoop)", "item_name": "Butter Scotch", "price": 40, "image": "food_items/item1.jpg", "description": "Creamy butterscotch ice cream."},
    {"id": "ic_ss_4", "category": "Ice Cream (Single Scoop)", "item_name": "Strawberry", "price": 40, "image": "food_items/item2.jpg", "description": "Sweet strawberry ice cream."},
    {"id": "ic_ss_5", "category": "Ice Cream (Single Scoop)", "item_name": "Black Current", "price": 40, "image": "food_items/item1.jpg", "description": "Tangy black currant ice cream."},
    {"id": "ic_ss_6", "category": "Ice Cream (Single Scoop)", "item_name": "Mango", "price": 40, "image": "food_items/item2.jpg", "description": "Tropical mango ice cream."},
    # Milkshake
    {"id": "ms_1", "category": "Milkshake", "item_name": "Tender Coconut Milkshake", "price": 70, "image": "food_items/item1.jpg", "description": "Refreshing milkshake made with tender coconut."},
    {"id": "ms_2", "category": "Milkshake", "item_name": "Vanilla Shake", "price": 70, "image": "food_items/item2.jpg", "description": "Classic vanilla flavored creamy milkshake."},
    {"id": "ms_3", "category": "Milkshake", "item_name": "Chocolate Shake", "price": 80, "image": "food_items/item1.jpg", "description": "Rich chocolate flavored creamy milkshake."},
    {"id": "ms_4", "category": "Milkshake", "item_name": "Butter Scotch Shake", "price": 80, "image": "food_items/item2.jpg", "description": "Creamy butterscotch flavored milkshake."},
    {"id": "ms_5", "category": "Milkshake", "item_name": "Mango Shake", "price": 80, "image": "food_items/item1.jpg", "description": "Sweet mango flavored creamy milkshake."},
    {"id": "ms_6", "category": "Milkshake", "item_name": "Black Currant Shake", "price": 80, "image": "food_items/item2.jpg", "description": "Tangy black currant flavored creamy milkshake."},
    {"id": "ms_7", "category": "Milkshake", "item_name": "Strawberry Shake", "price": 80, "image": "food_items/item1.jpg", "description": "Sweet strawberry flavored creamy milkshake."},
    {"id": "ms_8", "category": "Milkshake", "item_name": "Chikoo Shake", "price": 90, "image": "food_items/item2.jpg", "description": "Delicious Chikoo (Sapodilla) fruit milkshake."},
    {"id": "ms_9", "category": "Milkshake", "item_name": "Kit Kat Shake", "price": 90, "image": "food_items/item1.jpg", "description": "Milkshake blended with Kit Kat chocolate."},
    {"id": "ms_10", "category": "Milkshake", "item_name": "Apple Shake", "price": 80, "image": "food_items/item2.jpg", "description": "Refreshing apple flavored milkshake."},
    # Fresh Juice
    {"id": "fj_1", "category": "Fresh Juice", "item_name": "Orange Juice", "price": 75, "image": "food_items/item1.jpg", "description": "Freshly squeezed orange juice."},
    {"id": "fj_2", "category": "Fresh Juice", "item_name": "Watermelon Juice", "price": 70, "image": "food_items/item2.jpg", "description": "Refreshing watermelon juice."},
    {"id": "fj_3", "category": "Fresh Juice", "item_name": "Pomegranate Juice", "price": 80, "image": "food_items/item1.jpg", "description": "Freshly squeezed pomegranate juice."},
    {"id": "fj_4", "category": "Fresh Juice", "item_name": "Pineapple Juice", "price": 60, "image": "food_items/item2.jpg", "description": "Sweet and tangy pineapple juice."},
    {"id": "fj_5", "category": "Fresh Juice", "item_name": "Sweet Lime Juice", "price": 60, "image": "food_items/item1.jpg", "description": "Refreshing sweet lime juice."},
    {"id": "fj_6", "category": "Fresh Juice", "item_name": "Mosambi Juice", "price": 60, "image": "food_items/item2.jpg", "description": "Freshly squeezed Mosambi juice."},
    {"id": "fj_7", "category": "Fresh Juice", "item_name": "Lime Juice Soda (Sweet/Salt)", "price": 50, "image": "food_items/item1.jpg", "description": "Tangy lime juice with soda, sweet or salty."},
    {"id": "fj_8", "category": "Fresh Juice", "item_name": "Hot Milk", "price": 12, "image": "food_items/item2.jpg", "description": "Warm plain milk."},
    {"id": "fj_9", "category": "Fresh Juice", "item_name": "Lime Mint Mojito", "price": 70, "image": "food_items/item1.jpg", "description": "Refreshing mojito with lime and mint."},
    # Mojito
    {"id": "mj_1", "category": "Mojito", "item_name": "Tea", "price": 12, "image": "food_items/item2.jpg", "description": "Classic hot tea."},
    {"id": "mj_2", "category": "Mojito", "item_name": "Milk Mint", "price": 60, "image": "food_items/item1.jpg", "description": "Refreshing milk with a hint of mint."},
    {"id": "mj_3", "category": "Mojito", "item_name": "Filter Coffee", "price": 30, "image": "food_items/item2.jpg", "description": "Traditional South Indian filter coffee."},
    {"id": "mj_4", "category": "Mojito", "item_name": "Sweet Lime Mojito", "price": 60, "image": "food_items/item1.jpg", "description": "Sweet and tangy mojito with lime."},
    {"id": "mj_5", "category": "Mojito", "item_name": "Badam Milk (Hot)", "price": 70, "image": "food_items/item2.jpg", "description": "Warm milk infused with crushed almonds."},
    {"id": "mj_6", "category": "Mojito", "item_name": "Green Apple Mojito", "price": 60, "image": "food_items/item1.jpg", "description": "Refreshing mojito with crisp green apple."},
    {"id": "mj_7", "category": "Mojito", "item_name": "Lemon Tea", "price": 15, "image": "food_items/item2.jpg", "description": "Light and refreshing tea with lemon."},
    {"id": "mj_8", "category": "Mojito", "item_name": "Strawberry Mojito", "price": 60, "image": "food_items/item1.jpg", "description": "Sweet strawberry flavored mojito."},
    {"id": "mj_9", "category": "Mojito", "item_name": "Masala Tea", "price": 15, "image": "food_items/item1.jpg", "description": "Aromatic Indian spiced tea."},
    {"id": "mj_10", "category": "Mojito", "item_name": "Ginger Tea", "price": 15, "image": "food_items/item2.jpg", "description": "Warm tea infused with fresh ginger."},
    {"id": "mj_11", "category": "Mojito", "item_name": "Black Coffee", "price": 20, "image": "food_items/item1.jpg", "description": "Strong black coffee."},
    {"id": "mj_12", "category": "Mojito", "item_name": "Blueberry Mojito", "price": 60, "image": "food_items/item2.jpg", "description": "Sweet and tart blueberry flavored mojito."},
    {"id": "mj_13", "category": "Mojito", "item_name": "Sukku Malli Coffee", "price": 30, "image": "food_items/item1.jpg", "description": "Traditional South Indian herbal coffee."},
    {"id": "mj_14", "category": "Mojito", "item_name": "Pista Badamdu Milk", "price": 70, "image": "food_items/item2.jpg", "description": "Rich milk with pistachio and almond flavors."},
    {"id": "mj_15", "category": "Mojito", "item_name": "Green Tea", "price": 15, "image": "food_items/item1.jpg", "description": "Light and healthy green tea."},
    {"id": "mj_16", "category": "Mojito", "item_name": "Plain Milk", "price": 10, "image": "food_items/item2.jpg", "description": "Simple plain milk."},
    {"id": "mj_17", "category": "Mojito", "item_name": "Nattu Sarkarai Milk", "price": 25, "image": "food_items/item1.jpg", "description": "Traditional jaggery sweetened milk."},
    {"id": "mj_18", "category": "Mojito", "item_name": "Nattu Sarkarai Tea", "price": 25, "image": "food_items/item2.jpg", "description": "Traditional jaggery sweetened tea."},
    {"id": "mj_19", "category": "Mojito", "item_name": "Nattu Sarkarai Coffee", "price": 30, "image": "food_items/item1.jpg", "description": "Traditional jaggery sweetened coffee."},
    # Combos
    {"id": "c_1", "category": "Combos", "item_name": "Combo 1: Veg Sandwich + Veg Wrap + Mojito", "price": 199, "image": "food_items/item2.jpg", "description": "A delightful combo of Veg Sandwich, Veg Wrap, and a refreshing Mojito."},
    {"id": "c_2", "category": "Combos", "item_name": "Combo 2: Crispy Chicken Sandwich + Chicken Wrap + Ice Cream + Mojito", "price": 399, "image": "food_items/item1.jpg", "description": "Crispy Chicken Sandwich, Chicken Wrap, Ice Cream, and a Mojito for a fulfilling meal."},
    {"id": "c_3", "category": "Combos", "item_name": "Combo 3: Crispy Fried Chicken + Chicken Sandwich + Veg Pizza + Ice Cream + Mojito", "price": 399, "image": "food_items/item2.jpg", "description": "A grand combo with Crispy Fried Chicken, Chicken Sandwich, Veg Pizza, Ice Cream, and a Mojito."},
]